#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CiclicaApp_DB")]
	public partial class conexionlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public conexionlinqDataContext() : 
				base(global::Backend.Properties.Settings.Default.CiclicaApp_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarUsuario")]
		public int sp_IngresarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_NOMBRE", DbType="VarChar(200)")] string uSER_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PRIMER_APELLIDO", DbType="VarChar(150)")] string uSER_PRIMER_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_SEGUNDO_APELLIDO", DbType="VarChar(150)")] string uSER_SEGUNDO_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CORREO", DbType="VarChar(200)")] string uSER_CORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CONTRASENA", DbType="VarChar(50)")] string uSER_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_NOMBRE, uSER_PRIMER_APELLIDO, uSER_SEGUNDO_APELLIDO, uSER_CORREO, uSER_CONTRASENA, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(6)));
			errorDescripcion = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LoginUsuario")]
		public int SP_LoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(200)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasena, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerSession")]
		public ISingleResult<sp_ObtenerSessionResult> sp_ObtenerSession([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string session, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), session, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<sp_ObtenerSessionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarSession")]
		public int sp_IngresarSession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION_USER_ID", DbType="Int")] System.Nullable<int> sESSION_USER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION", DbType="VarChar(MAX)")] string sESSION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESSION_USER_ID, sESSION, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CerrarSesionesAntiguas")]
		public int sp_CerrarSesionesAntiguas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION", DbType="VarChar(MAX)")] string sESSION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESSION, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarRegistroCicloMenstrual")]
		public int sp_IngresarRegistroCicloMenstrual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaInicioCiclo", DbType="Date")] System.Nullable<System.DateTime> fechaInicioCiclo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionCiclo", DbType="Int")] System.Nullable<int> duracionCiclo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionMenstruacion", DbType="Int")] System.Nullable<int> duracionMenstruacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, fechaInicioCiclo, duracionCiclo, duracionMenstruacion, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(4)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorDescripcion = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MostrarHistorialAnticonceptivos")]
		public ISingleResult<sp_MostrarHistorialAnticonceptivosResult> sp_MostrarHistorialAnticonceptivos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_MostrarHistorialAnticonceptivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MostrarConsejos")]
		public ISingleResult<sp_MostrarConsejosResult> sp_MostrarConsejos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_MostrarConsejosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarNotificacion")]
		public int sp_ActualizarNotificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerAnticonceptivos")]
		public ISingleResult<sp_ObtenerAnticonceptivosResult> sp_ObtenerAnticonceptivos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_ObtenerAnticonceptivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarNotificacion")]
		public int sp_InsertarNotificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANTI_CONCEP_ID", DbType="Int")] System.Nullable<int> aNTI_CONCEP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNotifi", DbType="DateTime")] System.Nullable<System.DateTime> fechaNotifi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraNotifi", DbType="DateTime")] System.Nullable<System.DateTime> horaNotifi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID, aNTI_CONCEP_ID, fechaNotifi, horaNotifi);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FiltrarProductosPorColor")]
		public ISingleResult<sp_FiltrarProductosPorColorResult> sp_FiltrarProductosPorColor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ColorId", DbType="Int")] System.Nullable<int> colorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), colorId, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<sp_FiltrarProductosPorColorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FiltrarProductosPorRangoDePrecios")]
		public ISingleResult<sp_FiltrarProductosPorRangoDePreciosResult> sp_FiltrarProductosPorRangoDePrecios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioMin", DbType="Decimal(20,2)")] System.Nullable<decimal> precioMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioMax", DbType="Decimal(20,2)")] System.Nullable<decimal> precioMax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), precioMin, precioMax, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<sp_FiltrarProductosPorRangoDePreciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MostrarCategoriasProductos")]
		public ISingleResult<sp_MostrarCategoriasProductosResult> sp_MostrarCategoriasProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<sp_MostrarCategoriasProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerProductosPorCategoriaPorID")]
		public ISingleResult<SP_ObtenerProductosPorCategoriaPorIDResult> SP_ObtenerProductosPorCategoriaPorID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoriaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, categoriaID, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_ObtenerProductosPorCategoriaPorIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerHistorialCicloMenstrual")]
		public ISingleResult<sp_ObtenerHistorialCicloMenstrualResult> sp_ObtenerHistorialCicloMenstrual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<sp_ObtenerHistorialCicloMenstrualResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertarBiomarcadores")]
		public int spInsertarBiomarcadores([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="Int")] System.Nullable<int> user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CAM_CERVIX_ID", DbType="Int")] System.Nullable<int> cAM_CERVIX_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoAnimo_ID", DbType="Int")] System.Nullable<int> estadoAnimo_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sintomas_ID", DbType="Int")] System.Nullable<int> sintomas_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="T_SANG_ID", DbType="Int")] System.Nullable<int> t_SANG_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANT_MENST_ID", DbType="Int")] System.Nullable<int> cANT_MENST_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MocoCervix_ID", DbType="Int")] System.Nullable<int> mocoCervix_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoFlujo_ID", DbType="Int")] System.Nullable<int> tipoFlujo_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REG_FECHA", DbType="Date")] System.Nullable<System.DateTime> rEG_FECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REG_NOTAS", DbType="VarChar(MAX)")] string rEG_NOTAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REG_TEMP_BASAL", DbType="Decimal(4,1)")] System.Nullable<decimal> rEG_TEMP_BASAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REG_LIBIDO", DbType="VarChar(50)")] string rEG_LIBIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnId", DbType="Int")] ref System.Nullable<int> returnId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, cAM_CERVIX_ID, estadoAnimo_ID, sintomas_ID, t_SANG_ID, cANT_MENST_ID, mocoCervix_ID, tipoFlujo_ID, rEG_FECHA, rEG_NOTAS, rEG_TEMP_BASAL, rEG_LIBIDO, returnId, errorId, errorMessage);
			returnId = ((System.Nullable<int>)(result.GetParameterValue(12)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(13)));
			errorMessage = ((string)(result.GetParameterValue(14)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerBiomarcadores")]
		public ISingleResult<spObtenerBiomarcadoresResult> spObtenerBiomarcadores([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="Int")] System.Nullable<int> user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, idReturn, errorId, errorMessage);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorMessage = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<spObtenerBiomarcadoresResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_ObtenerSessionResult
	{
		
		private int _SESSION_ID;
		
		private int _SESSION_USER_ID;
		
		private string _SESSION;
		
		private System.Nullable<System.DateTime> _SESSION_FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _SESSION_FECHA_FINAL;
		
		private System.Nullable<bool> _SESSION_ESTADO;
		
		public sp_ObtenerSessionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_ID", DbType="Int NOT NULL")]
		public int SESSION_ID
		{
			get
			{
				return this._SESSION_ID;
			}
			set
			{
				if ((this._SESSION_ID != value))
				{
					this._SESSION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_USER_ID", DbType="Int NOT NULL")]
		public int SESSION_USER_ID
		{
			get
			{
				return this._SESSION_USER_ID;
			}
			set
			{
				if ((this._SESSION_USER_ID != value))
				{
					this._SESSION_USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SESSION
		{
			get
			{
				return this._SESSION;
			}
			set
			{
				if ((this._SESSION != value))
				{
					this._SESSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_FECHA_INICIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> SESSION_FECHA_INICIO
		{
			get
			{
				return this._SESSION_FECHA_INICIO;
			}
			set
			{
				if ((this._SESSION_FECHA_INICIO != value))
				{
					this._SESSION_FECHA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_FECHA_FINAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> SESSION_FECHA_FINAL
		{
			get
			{
				return this._SESSION_FECHA_FINAL;
			}
			set
			{
				if ((this._SESSION_FECHA_FINAL != value))
				{
					this._SESSION_FECHA_FINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_ESTADO", DbType="Bit")]
		public System.Nullable<bool> SESSION_ESTADO
		{
			get
			{
				return this._SESSION_ESTADO;
			}
			set
			{
				if ((this._SESSION_ESTADO != value))
				{
					this._SESSION_ESTADO = value;
				}
			}
		}
	}
	
	public partial class sp_MostrarHistorialAnticonceptivosResult
	{
		
		private string _ANTI_CONCEP_NOMBRE;
		
		private System.DateTime _NOTIFI_START_DATE;
		
		private System.Nullable<System.DateTime> _NOTIFI_FECHA_FINAL;
		
		public sp_MostrarHistorialAnticonceptivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANTI_CONCEP_NOMBRE
		{
			get
			{
				return this._ANTI_CONCEP_NOMBRE;
			}
			set
			{
				if ((this._ANTI_CONCEP_NOMBRE != value))
				{
					this._ANTI_CONCEP_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFI_START_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime NOTIFI_START_DATE
		{
			get
			{
				return this._NOTIFI_START_DATE;
			}
			set
			{
				if ((this._NOTIFI_START_DATE != value))
				{
					this._NOTIFI_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFI_FECHA_FINAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> NOTIFI_FECHA_FINAL
		{
			get
			{
				return this._NOTIFI_FECHA_FINAL;
			}
			set
			{
				if ((this._NOTIFI_FECHA_FINAL != value))
				{
					this._NOTIFI_FECHA_FINAL = value;
				}
			}
		}
	}
	
	public partial class sp_MostrarConsejosResult
	{
		
		private int _CONSJ_ID;
		
		private string _CONSJ_CONSEJO;
		
		public sp_MostrarConsejosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSJ_ID", DbType="Int NOT NULL")]
		public int CONSJ_ID
		{
			get
			{
				return this._CONSJ_ID;
			}
			set
			{
				if ((this._CONSJ_ID != value))
				{
					this._CONSJ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSJ_CONSEJO", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CONSJ_CONSEJO
		{
			get
			{
				return this._CONSJ_CONSEJO;
			}
			set
			{
				if ((this._CONSJ_CONSEJO != value))
				{
					this._CONSJ_CONSEJO = value;
				}
			}
		}
	}
	
	public partial class sp_ObtenerAnticonceptivosResult
	{
		
		private int _ANTI_CONCEP_ID;
		
		private string _ANTI_CONCEP_NOMBRE;
		
		private string _ANTI_EFECTIVIDAD;
		
		public sp_ObtenerAnticonceptivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_ID", DbType="Int NOT NULL")]
		public int ANTI_CONCEP_ID
		{
			get
			{
				return this._ANTI_CONCEP_ID;
			}
			set
			{
				if ((this._ANTI_CONCEP_ID != value))
				{
					this._ANTI_CONCEP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANTI_CONCEP_NOMBRE
		{
			get
			{
				return this._ANTI_CONCEP_NOMBRE;
			}
			set
			{
				if ((this._ANTI_CONCEP_NOMBRE != value))
				{
					this._ANTI_CONCEP_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_EFECTIVIDAD", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ANTI_EFECTIVIDAD
		{
			get
			{
				return this._ANTI_EFECTIVIDAD;
			}
			set
			{
				if ((this._ANTI_EFECTIVIDAD != value))
				{
					this._ANTI_EFECTIVIDAD = value;
				}
			}
		}
	}
	
	public partial class sp_FiltrarProductosPorColorResult
	{
		
		private int _PROD_ID;
		
		private string _PROD_NOMBRE;
		
		private int _PROD_CANTIDAD;
		
		private decimal _PROD_PRECIO;
		
		public sp_FiltrarProductosPorColorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_ID", DbType="Int NOT NULL")]
		public int PROD_ID
		{
			get
			{
				return this._PROD_ID;
			}
			set
			{
				if ((this._PROD_ID != value))
				{
					this._PROD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_NOMBRE", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PROD_NOMBRE
		{
			get
			{
				return this._PROD_NOMBRE;
			}
			set
			{
				if ((this._PROD_NOMBRE != value))
				{
					this._PROD_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_CANTIDAD", DbType="Int NOT NULL")]
		public int PROD_CANTIDAD
		{
			get
			{
				return this._PROD_CANTIDAD;
			}
			set
			{
				if ((this._PROD_CANTIDAD != value))
				{
					this._PROD_CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_PRECIO", DbType="Decimal(20,2) NOT NULL")]
		public decimal PROD_PRECIO
		{
			get
			{
				return this._PROD_PRECIO;
			}
			set
			{
				if ((this._PROD_PRECIO != value))
				{
					this._PROD_PRECIO = value;
				}
			}
		}
	}
	
	public partial class sp_FiltrarProductosPorRangoDePreciosResult
	{
		
		private int _PROD_ID;
		
		private string _PROD_NOMBRE;
		
		private int _PROD_CANTIDAD;
		
		private decimal _PROD_PRECIO;
		
		public sp_FiltrarProductosPorRangoDePreciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_ID", DbType="Int NOT NULL")]
		public int PROD_ID
		{
			get
			{
				return this._PROD_ID;
			}
			set
			{
				if ((this._PROD_ID != value))
				{
					this._PROD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_NOMBRE", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PROD_NOMBRE
		{
			get
			{
				return this._PROD_NOMBRE;
			}
			set
			{
				if ((this._PROD_NOMBRE != value))
				{
					this._PROD_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_CANTIDAD", DbType="Int NOT NULL")]
		public int PROD_CANTIDAD
		{
			get
			{
				return this._PROD_CANTIDAD;
			}
			set
			{
				if ((this._PROD_CANTIDAD != value))
				{
					this._PROD_CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_PRECIO", DbType="Decimal(20,2) NOT NULL")]
		public decimal PROD_PRECIO
		{
			get
			{
				return this._PROD_PRECIO;
			}
			set
			{
				if ((this._PROD_PRECIO != value))
				{
					this._PROD_PRECIO = value;
				}
			}
		}
	}
	
	public partial class sp_MostrarCategoriasProductosResult
	{
		
		private int _CTG_PROD_ID;
		
		private string _CTG_PROD_NOMBRE;
		
		private string _CTG_PROD_DESCRIPCION;
		
		public sp_MostrarCategoriasProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTG_PROD_ID", DbType="Int NOT NULL")]
		public int CTG_PROD_ID
		{
			get
			{
				return this._CTG_PROD_ID;
			}
			set
			{
				if ((this._CTG_PROD_ID != value))
				{
					this._CTG_PROD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTG_PROD_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CTG_PROD_NOMBRE
		{
			get
			{
				return this._CTG_PROD_NOMBRE;
			}
			set
			{
				if ((this._CTG_PROD_NOMBRE != value))
				{
					this._CTG_PROD_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTG_PROD_DESCRIPCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CTG_PROD_DESCRIPCION
		{
			get
			{
				return this._CTG_PROD_DESCRIPCION;
			}
			set
			{
				if ((this._CTG_PROD_DESCRIPCION != value))
				{
					this._CTG_PROD_DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerProductosPorCategoriaPorIDResult
	{
		
		private int _PROD_ID;
		
		private string _PROD_SKU;
		
		private string _PROD_NOMBRE;
		
		private int _PROD_CANTIDAD;
		
		private decimal _PROD_PRECIO;
		
		private System.DateTime _PROD_FECHA_INGR;
		
		private bool _PROD_STATUS;
		
		private int _PROD_TIPO_ID;
		
		public SP_ObtenerProductosPorCategoriaPorIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_ID", DbType="Int NOT NULL")]
		public int PROD_ID
		{
			get
			{
				return this._PROD_ID;
			}
			set
			{
				if ((this._PROD_ID != value))
				{
					this._PROD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_SKU", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PROD_SKU
		{
			get
			{
				return this._PROD_SKU;
			}
			set
			{
				if ((this._PROD_SKU != value))
				{
					this._PROD_SKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_NOMBRE", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PROD_NOMBRE
		{
			get
			{
				return this._PROD_NOMBRE;
			}
			set
			{
				if ((this._PROD_NOMBRE != value))
				{
					this._PROD_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_CANTIDAD", DbType="Int NOT NULL")]
		public int PROD_CANTIDAD
		{
			get
			{
				return this._PROD_CANTIDAD;
			}
			set
			{
				if ((this._PROD_CANTIDAD != value))
				{
					this._PROD_CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_PRECIO", DbType="Decimal(20,2) NOT NULL")]
		public decimal PROD_PRECIO
		{
			get
			{
				return this._PROD_PRECIO;
			}
			set
			{
				if ((this._PROD_PRECIO != value))
				{
					this._PROD_PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_FECHA_INGR", DbType="DateTime NOT NULL")]
		public System.DateTime PROD_FECHA_INGR
		{
			get
			{
				return this._PROD_FECHA_INGR;
			}
			set
			{
				if ((this._PROD_FECHA_INGR != value))
				{
					this._PROD_FECHA_INGR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_STATUS", DbType="Bit NOT NULL")]
		public bool PROD_STATUS
		{
			get
			{
				return this._PROD_STATUS;
			}
			set
			{
				if ((this._PROD_STATUS != value))
				{
					this._PROD_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_TIPO_ID", DbType="Int NOT NULL")]
		public int PROD_TIPO_ID
		{
			get
			{
				return this._PROD_TIPO_ID;
			}
			set
			{
				if ((this._PROD_TIPO_ID != value))
				{
					this._PROD_TIPO_ID = value;
				}
			}
		}
	}
	
	public partial class sp_ObtenerHistorialCicloMenstrualResult
	{
		
		private int _MENSTRUACION_ID;
		
		private int _USUARIO_ID;
		
		private System.Nullable<System.DateTime> _CICMENS_FECHA_INICIO_CICLO;
		
		private int _CICMENS_DURACION_CICLO;
		
		private int _CICMENS_DURACION_MENSTRUACION;
		
		public sp_ObtenerHistorialCicloMenstrualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSTRUACION_ID", DbType="Int NOT NULL")]
		public int MENSTRUACION_ID
		{
			get
			{
				return this._MENSTRUACION_ID;
			}
			set
			{
				if ((this._MENSTRUACION_ID != value))
				{
					this._MENSTRUACION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int NOT NULL")]
		public int USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CICMENS_FECHA_INICIO_CICLO", DbType="Date")]
		public System.Nullable<System.DateTime> CICMENS_FECHA_INICIO_CICLO
		{
			get
			{
				return this._CICMENS_FECHA_INICIO_CICLO;
			}
			set
			{
				if ((this._CICMENS_FECHA_INICIO_CICLO != value))
				{
					this._CICMENS_FECHA_INICIO_CICLO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CICMENS_DURACION_CICLO", DbType="Int NOT NULL")]
		public int CICMENS_DURACION_CICLO
		{
			get
			{
				return this._CICMENS_DURACION_CICLO;
			}
			set
			{
				if ((this._CICMENS_DURACION_CICLO != value))
				{
					this._CICMENS_DURACION_CICLO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CICMENS_DURACION_MENSTRUACION", DbType="Int NOT NULL")]
		public int CICMENS_DURACION_MENSTRUACION
		{
			get
			{
				return this._CICMENS_DURACION_MENSTRUACION;
			}
			set
			{
				if ((this._CICMENS_DURACION_MENSTRUACION != value))
				{
					this._CICMENS_DURACION_MENSTRUACION = value;
				}
			}
		}
	}
	
	public partial class spObtenerBiomarcadoresResult
	{
		
		private int _REGISTRO_ID;
		
		private int _Reg_User_ID;
		
		private string _CAM_CVX_ALTURA;
		
		private string _CAM_CVX_APERTURA_CERVX;
		
		private string _CAM_CVX_DESCRIPCION;
		
		private string _EST_ANIM_NOMBRE;
		
		private string _SINT_NOMBRE;
		
		private string _TSANG_NOMBRE;
		
		private string _CM_NOMBRE;
		
		private string _MC_OLOR;
		
		private string _MC_CANTIDAD;
		
		private System.Nullable<System.DateTime> _REG_FECHA;
		
		private string _REG_NOTAS;
		
		private System.Nullable<decimal> _REG_TEMP_BASAL;
		
		private string _REG_LIBIDO;
		
		private string _TPO_F_OLOR;
		
		private string _TPO_F_CANTIDAD;
		
		public spObtenerBiomarcadoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRO_ID", DbType="Int NOT NULL")]
		public int REGISTRO_ID
		{
			get
			{
				return this._REGISTRO_ID;
			}
			set
			{
				if ((this._REGISTRO_ID != value))
				{
					this._REGISTRO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_User_ID", DbType="Int NOT NULL")]
		public int Reg_User_ID
		{
			get
			{
				return this._Reg_User_ID;
			}
			set
			{
				if ((this._Reg_User_ID != value))
				{
					this._Reg_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAM_CVX_ALTURA", DbType="VarChar(50)")]
		public string CAM_CVX_ALTURA
		{
			get
			{
				return this._CAM_CVX_ALTURA;
			}
			set
			{
				if ((this._CAM_CVX_ALTURA != value))
				{
					this._CAM_CVX_ALTURA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAM_CVX_APERTURA_CERVX", DbType="VarChar(50)")]
		public string CAM_CVX_APERTURA_CERVX
		{
			get
			{
				return this._CAM_CVX_APERTURA_CERVX;
			}
			set
			{
				if ((this._CAM_CVX_APERTURA_CERVX != value))
				{
					this._CAM_CVX_APERTURA_CERVX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAM_CVX_DESCRIPCION", DbType="VarChar(255)")]
		public string CAM_CVX_DESCRIPCION
		{
			get
			{
				return this._CAM_CVX_DESCRIPCION;
			}
			set
			{
				if ((this._CAM_CVX_DESCRIPCION != value))
				{
					this._CAM_CVX_DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_ANIM_NOMBRE", DbType="VarChar(70)")]
		public string EST_ANIM_NOMBRE
		{
			get
			{
				return this._EST_ANIM_NOMBRE;
			}
			set
			{
				if ((this._EST_ANIM_NOMBRE != value))
				{
					this._EST_ANIM_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINT_NOMBRE", DbType="VarChar(70)")]
		public string SINT_NOMBRE
		{
			get
			{
				return this._SINT_NOMBRE;
			}
			set
			{
				if ((this._SINT_NOMBRE != value))
				{
					this._SINT_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSANG_NOMBRE", DbType="VarChar(70)")]
		public string TSANG_NOMBRE
		{
			get
			{
				return this._TSANG_NOMBRE;
			}
			set
			{
				if ((this._TSANG_NOMBRE != value))
				{
					this._TSANG_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CM_NOMBRE", DbType="VarChar(70)")]
		public string CM_NOMBRE
		{
			get
			{
				return this._CM_NOMBRE;
			}
			set
			{
				if ((this._CM_NOMBRE != value))
				{
					this._CM_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_OLOR", DbType="VarChar(70)")]
		public string MC_OLOR
		{
			get
			{
				return this._MC_OLOR;
			}
			set
			{
				if ((this._MC_OLOR != value))
				{
					this._MC_OLOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_CANTIDAD", DbType="VarChar(70)")]
		public string MC_CANTIDAD
		{
			get
			{
				return this._MC_CANTIDAD;
			}
			set
			{
				if ((this._MC_CANTIDAD != value))
				{
					this._MC_CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_FECHA", DbType="Date")]
		public System.Nullable<System.DateTime> REG_FECHA
		{
			get
			{
				return this._REG_FECHA;
			}
			set
			{
				if ((this._REG_FECHA != value))
				{
					this._REG_FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_NOTAS", DbType="VarChar(MAX)")]
		public string REG_NOTAS
		{
			get
			{
				return this._REG_NOTAS;
			}
			set
			{
				if ((this._REG_NOTAS != value))
				{
					this._REG_NOTAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_TEMP_BASAL", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> REG_TEMP_BASAL
		{
			get
			{
				return this._REG_TEMP_BASAL;
			}
			set
			{
				if ((this._REG_TEMP_BASAL != value))
				{
					this._REG_TEMP_BASAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_LIBIDO", DbType="VarChar(50)")]
		public string REG_LIBIDO
		{
			get
			{
				return this._REG_LIBIDO;
			}
			set
			{
				if ((this._REG_LIBIDO != value))
				{
					this._REG_LIBIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPO_F_OLOR", DbType="VarChar(70)")]
		public string TPO_F_OLOR
		{
			get
			{
				return this._TPO_F_OLOR;
			}
			set
			{
				if ((this._TPO_F_OLOR != value))
				{
					this._TPO_F_OLOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPO_F_CANTIDAD", DbType="VarChar(70)")]
		public string TPO_F_CANTIDAD
		{
			get
			{
				return this._TPO_F_CANTIDAD;
			}
			set
			{
				if ((this._TPO_F_CANTIDAD != value))
				{
					this._TPO_F_CANTIDAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
